export const products = [
  {
    id: 1,
    image: "/assets/product-1.PNG",
    title: "Graphic Design",
    department: "English Department",
    oldPrice: 16.48,
    newPrice: 6.48,
  },
  {
    id: 2,
    image: "/assets/product-2.PNG",
    title: "Graphic Design",
    department: "English Department",
    oldPrice: 16.48,
    newPrice: 6.48,
  },
  {
    id: 3,
    image: "/assets/product-3.PNG",
    title: "Graphic Design",
    department: "English Department",
    oldPrice: 16.48,
    newPrice: 6.48,
  },
  {
    id: 4,
    image: "/assets/product-1.PNG",
    title: "Graphic Design",
    department: "English Department",
    oldPrice: 16.48,
    newPrice: 6.48,
  },
  {
    id: 5,
    image: "/assets/product-2.PNG",
    title: "Graphic Design",
    department: "English Department",
    oldPrice: 16.48,
    newPrice: 6.48,
  },
  {
    id: 6,
    image: "/assets/product-3.PNG",
    title: "Graphic Design",
    department: "English Department",
    oldPrice: 16.48,
    newPrice: 6.48,
  },
];